### ISSUE TITLE
Add default config for the background-color

### ISSUE THREAD

**Issue by tony612** [atom/wrap-guide#11]
Why not add default config for the background-color?
like this:

``` css
@import "syntax-variables";
.editor .wrap-guide {
  background-color: @syntax-cursor-color;
  opacity: 0.5;
}
```
