### ISSUE TITLE
Multiple wrap guides

### ISSUE THREAD

**Issue by piranna** [atom/wrap-guide#14]
Add support to define several rules, both vertical and horizontal ones. Horizontal ones should repeat themselves the biggest number of lines that's specified, for example to mark header, footer and pagination areas.

**Comment by bnu** [comment]
+1

**Comment by theoretick** [comment]
This would be super useful +1

**Comment by nevir** [comment]
+1

**Comment by SalGnt** [comment]
+1

**Comment by khalidabuhakmeh** [comment]
+1

**Comment by wyand** [comment]
another :+1:... would love to have 50/72 for git commits.

**Comment by calebmeyer** [comment]
@vicary I'll second that. I'd love to see both 80 and 120, representing my preferred and maximum line lengths, respectively.
In sublime text's settings, rulers is an array.

**Comment by lexicalunit** [comment]
[multi-wrap-guide](https://atom.io/packages/multi-wrap-guide) might be what y'all are looking for. It's based on [omni-ruler](https://atom.io/packages/omni-ruler), but I added some fancy new features like being able to adjust guides by simply dragging them.

**Comment by piranna** [comment]
@lexicalunit your fork seems nice, and I've seen you have on the to-do section the hability to define the rules based on language, but how can I be able to set colors for each ruler?

**Comment by lexicalunit** [comment]
@piranna You mean different colors for each individual ruler? Or just the ability to change the color of all the rulers as a whole? If the latter you can use your style.less to override the color. If the former, please feel free to open an issue against my library and I'll try to implement it when I have some free time.

**Comment by piranna** [comment]
One color for each ruler ;-) I've filled it at https://github.com/lexicalunit/multi-wrap-guide/issues/3

**Comment by maasha** [comment]
+1

**Comment by Mottie** [comment]
Alternatively, you can add some CSS to do the same thing... add this to your Atom stylesheet

```css
atom-text-editor .line {
  background: linear-gradient(
    to right, transparent 0%,
    transparent 80ch,  rgba(255, 0, 0, .3) 80ch,  rgba(255, 0, 0, .3) 80.1ch,  transparent 80.1ch,
    transparent 100ch, rgba(255, 0, 0, .3) 100ch, rgba(255, 0, 0, .3) 100.1ch, transparent 100.1ch,
    transparent 100%
  ) !important;
}
```

The above adds two vertical lines at 80 and 100 characters:
* Don't change the `transparent` color definitions.
* Adjust the color (in two places) as desired
* Adjust the `80ch` or `100ch` (in two places) to set the start of the guide.
* Adjust the `80.1ch` or `100.1ch` (in two places) to set the width of the guide.

I use a very similar method in my [GitHub Code Guides](https://greasyfork.org/en/scripts/22674-github-code-guides) userscript.

**Comment by tzvetkoff** [comment]
Here's my current solution for 3 rulers, based on @Mottie's snippet:

``` less
/* Preferred line length is set to 120ch */
atom-text-editor .wrap-guide::before, atom-text-editor .wrap-guide::after {
  content: '';
  position: absolute;
  z-index: 3;
  left: -20ch;
  top: 0;
  height: 100%;
  width: 1px;
  background-color: rgba(197, 200, 198, 0.1);
}
atom-text-editor .wrap-guide::after {
  left: -40ch;
}
```

Anyway, I would really appreciate support for this in the future.
