### ISSUE TITLE
Shade Region to Right of Wrap Guide

### ISSUE THREAD

**Issue by JosephTLyons** [atom/wrap-guide#78]
It would be great if you could change a toggle that would shade the entire region to the right of the wrap guide (like Xcode), to help those with eyes that aren't as great see the line.

See my post [here](https://discuss.atom.io/t/package-to-shade-the-region-to-the-right-of-the-max-column-indicator/53187).

**Comment by rsese** [comment]
Thanks for the feedback @JosephTLyons 👍  I'll mention it to the team but my guess is we likely won't introduce an option for this since it can be added with some CSS like DamnedScholar mentions and is called out in the README:

https://github.com/atom/wrap-guide#configuration

E.g. this seems to work for me in my `styles.less` file:

```css
atom-text-editor .wrap-guide {
  width: 100%;
  background-color: rgba(80, 80, 80, 0.4);
}
```

![wrap-shade](https://github-slack.s3.amazonaws.com/monosnap/README.md__githubteletype_2018-03-12_15-57-16.png)
